firebase:
  token_path: "./firebase_token.json"
ngrok:
  port: "8444"
  token: "23ORZOPU4U7aASMSoP25uNfUzTT_7CYoused57rzj9yPTCYgy"
youtube_dl:
  audio_format: "mp3"
  audio_quality: 5
melon_chart:
  top: 40
  ballade: 10
  dance: 1
  hiphop: 1
  rnb: 1
  indie: 1
  rock: 1
  trot: 1
  folk: 1

  # Api Url created like : http://localhost:{ngrok.port}/{api.version}/{api_name}
api:
  version: "v1"
  config_api: "/config"
  audio_api: "/audio/{videoID}"
  log_api: "/log/{page}"
  melon_api: "/melon"
view:
  path: "./view/web/"