firebase:
  token_path: "./firebase_token.json"
ngrok:
  port: "8444"
  token: "23ORZOPU4U7aASMSoP25uNfUzTT_7CYoused57rzj9yPTCYgy"
youtube_dl:
  audio_format: "mp3"
  audio_quality: 5
melon_chart:
  top: 40
  ballade: 0
  dance: 0
  hiphop: 0
  rnb: 0
  indie: 0
  rock: 0
  trot: 0
  folk: 0
logger:
  path: "./log"
  # Api Url created like : http://localhost:{ngrok.port}/{api.version}/{api_name}
api:
  version: "v1"
  config_api: "/config"
  audio_api: "/audio/{videoID}"
  log_api: "/logger/{page}"
  melon_api: "/melon"
view:
  path: "./view/web/"